# Použij oficiální Python image
FROM python:3.11-slim

# Nastav pracovní adresář
WORKDIR /app

# Zkopíruj soubory
COPY . /app

# Nainstaluj dependencies
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose port, Cloud Run používá $PORT
ENV PORT 8080

# Spusť server
CMD exec uvicorn main:app --host 0.0.0.0 --port $PORT
